spring:
  profiles:
    active: local
server:
  port: 7001

kafkaTopicNews: broadcast-news-alerts
kafkaTopicBreakingNews: broadcast-breaking-news

---
spring:
  profiles: local
  kafka:
    template:
      default-topic: broadcast-news-alerts
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 500
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
  datasource:
    url: jdbc:h2:mem:product-producer-db

