spring:
  profiles:
    active: local
server:
  port: 7000

kafkaTopicNews: broadcast-news-alerts
kafkaTopicBreakingNews: broadcast-breaking-news

---
spring:
  profiles: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: news-event-listener-group




